platform :ios,'8.0'
inhibit_all_warnings!

target "WTDemo" do
    #基础组件
    pod 'WTBaseCore', :git => "https://github.com/jienliang000/WTBaseCore.git"
    pod 'WTImagePicker', :git => "https://github.com/jienliang000/WTImagePicker.git"  #相机图片选择和拍照
    pod 'WTPagerController', :git => "https://github.com/jienliang000/WTPagerController.git"
    #业务数据和自定义View
    pod 'QLBusiness', :git => "https://github.com/aliang124/QLBusiness.git"
end

